language: node_js
node_js:
  - "9"
sudo: false
dist: trusty
branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install

script:
  # run build script specified in package.json
  - npm build --base-href https://alimol.github.io/portalfe
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: 'e8a9039cb5959d23be45f4c9fae8a1f180a13929'
    local_dir: dist/STaaSPortalFE
    on:
      branch: master
