language: node_js
node_js:
  - "9"
sudo: false
dist: trusty
branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install

script:
  # run build script specified in package.json
  - npm run clean && npm run prettier:ci && ng lint && ng test --configuration=test --browsers ChromeTravisCi && ng e2e && npm run cy:ci && npm run accessibility && npm run build:prod -- --deploy-url /portalfe/ --base-href /portalfe
  # call script for deploying of produced artifacts

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/STaaSPortalFE
    on:
      branch: master
