language: node_js
node_js:
  - "9"
sudo: false
dist: trusty
branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install

script:
  # run build script specified in package.json
  - npm ci
  # call script for deploying of produced artifacts

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/STaaSPortalFE
    on:
      branch: master
